set_property PACKAGE_PIN W5 [get_ports Clock_100Mhz]
set_property IOSTANDARD LVCMOS33 [get_ports Clock_100Mhz]
#seven-segment LED display
set_property PACKAGE_PIN W7 [get_ports {LED_Seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_Seg[6]}]
set_property PACKAGE_PIN W6 [get_ports {LED_Seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_Seg[5]}]
set_property PACKAGE_PIN U8 [get_ports {LED_Seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_Seg[4]}]
set_property PACKAGE_PIN V8 [get_ports {LED_Seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_Seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {LED_Seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_Seg[2]}]
set_property PACKAGE_PIN V5 [get_ports {LED_Seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_Seg[1]}]
set_property PACKAGE_PIN U7 [get_ports {LED_Seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_Seg[0]}]
set_property PACKAGE_PIN U2 [get_ports {Anode_Activate[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[0]}]
set_property PACKAGE_PIN U4 [get_ports {Anode_Activate[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[1]}]
set_property PACKAGE_PIN V4 [get_ports {Anode_Activate[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[2]}]
set_property PACKAGE_PIN W4 [get_ports {Anode_Activate[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[3]}]
#Switches
set_property PACKAGE_PIN V16 [get_ports {In_num[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {In_num[0]}]
set_property PACKAGE_PIN W16 [get_ports {In_num[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {In_num[1]}]
set_property PACKAGE_PIN W17 [get_ports {In_num[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {In_num[2]}]
set_property PACKAGE_PIN W15 [get_ports {In_num[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {In_num[3]}]
#Button
set_property PACKAGE_PIN V17 [get_ports {reset}]
set_property IOSTANDARD LVCMOS33 [get_ports {reset}]

